### ISSUE TITLE
runit_service resource does not create service

### ISSUE THREAD

**Issue by johnbyrneio** [chef-cookbooks/runit#210]
### Cookbook version
3.0.3

### Chef-client version
12.17.44

### Platform Details
CentOS 6.8

### Scenario:
When the push-jobs cookbook calls the runit_service resource the service is not created. Several resources seem to be erroneously skipped. 

This commit seems to be the culprit: https://github.com/chef-cookbooks/runit/commit/edb8c8f68fd71690fdf5c2da097468e97ba516e7

The resource behaves as expected in 3.0.2

### Steps to Reproduce:
Add 'push-jobs' to run list of a node and don't constrain the version of 'runit'

### Expected Result:
Service created and running

### Actual Result:
```
Recipe: push-jobs::service
         * push_jobs_service_runit[push-jobs] action start
         Recipe: runit::default
           * service[runit] action nothing (skipped due to action :nothing)
           * execute[start-runsvdir] action nothing (skipped due to action :nothing)
         Recipe: yum-epel::default
           * yum_repository[epel] action create
             * template[/etc/yum.repos.d/epel.repo] action create (up to date)
             * execute[yum clean metadata epel] action nothing (skipped due to action :nothing)
             * execute[yum-makecache-epel] action nothing (skipped due to action :nothing)
             * ruby_block[yum-cache-reload-epel] action nothing (skipped due to action :nothing)
       (up to date)
         Recipe: runit::default
           * packagecloud_repo[imeyer/runit] action add
             * yum_package[pygpgme] action install (up to date)
             * log[pygpgme_warning] action write (skipped due to not_if)
             * ruby_block[disable repo_gpgcheck if no pygpgme] action run (skipped due to not_if)
             * template[/etc/yum.repos.d/imeyer_runit.repo] action create (up to date)
             * execute[yum-makecache-imeyer_runit] action nothing (skipped due to action :nothing)
             * ruby_block[yum-cache-reload-imeyer_runit] action nothing (skipped due to action :nothing)
       (up to date)
           * yum_package[runit] action install (up to date)
           * service[runsvdir-start] action start (skipped due to only_if)
           * service[runsvdir-start] action enable (skipped due to only_if)
         Recipe: <Dynamically Defined Resource>
           * service[opscode-push-jobs-client] action nothing (skipped due to action :nothing)
           * runit_service[opscode-push-jobs-client] action stop

             ================================================================================
             Error executing action `stop` on resource 'runit_service[opscode-push-jobs-client]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0, 100], but received '1'
             ---- Begin output of /sbin/sv status /etc/service/opscode-push-jobs-client ----
             STDOUT: fail: /etc/service/opscode-push-jobs-client: unable to change to service directory: file does not exist
             STDERR:
             ---- End output of /sbin/sv status /etc/service/opscode-push-jobs-client ----
             Ran /sbin/sv status /etc/service/opscode-push-jobs-client returned 1

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/runit/libraries/helpers.rb:162:in `safe_sv_shellout'
             /tmp/kitchen/cache/cookbooks/runit/libraries/helpers.rb:97:in `running?'
             /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:343:in `block in <class:RunitService>'
```

**Comment by kondapally1989** [comment]
Hi i am also getting the above issue but in RHEL 6.

@johnbyrneio  were you able to solve the problem?

**Comment by DanielRedOak** [comment]
👍  for having this addressed.  I cant seem to find a version that will function reliably with the Jenkins cookbook which is a big disappointment

**Comment by kondapally1989** [comment]
Well I was able to bypass this by creating folder /etc/service/opscode-push-jobs-client after cookbook run fails for first time and re running the cookbook. i don't how much of this is correct but was able to successfully configure the push-job client.

**Comment by tas50** [comment]
@johnbyrneio I'm looking into what may have caused this. The commit you pointed to may be the culprit, but that is the right change to make. The method it calls actually adds the sv bin command to the shellout string so before we had a bogus command which always failed. That method always failing may have led to things working, but it was a side effect not the desired state. I'm looking though. If you're still around any chance you can tell me what push-jobs cookbook release you're on?

**Comment by tas50** [comment]
Closing this since I haven't heard back and @johnbyrneio is at a new gig.
