### ISSUE TITLE
chef-server-ctl reconfigure failed in Ubuntu 14.04, chef v12.3.1

### ISSUE THREAD

**Issue by patrickcat** [chef-cookbooks/runit#218]
### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
ubuntu 14.04

### Scenario:
[What you are trying to achieve and you can't?]
After install chef-server, run chef-server-ctl reconfigure for the first time, and then failed.

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
- download chef server v12.14.1, or v12.3.1
- install it in ubuntu 16, or 14 with dpkg -i xxxxxx.deb
- run 'chef-server-ctl reconfigure' 
then errors come out. 

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
it's should be ok since it's the very begining of use chef

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

it's so strange that it fails like it does not support ubuntu at all.

**Comment by patrickcat** [comment]
Recipe: private-chef::rabbitmq
  * execute[/opt/opscode/bin/private-chef-ctl start rabbitmq] action run





    
    ================================================================================
    Error executing action `run` on resource 'execute[/opt/opscode/bin/private-chef-ctl start rabbitmq]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/bin/private-chef-ctl start rabbitmq ----
    STDOUT: warning: rabbitmq: unable to open supervise/ok: file does not exist
    STDERR: 
    ---- End output of /opt/opscode/bin/private-chef-ctl start rabbitmq ----
    Ran /opt/opscode/bin/private-chef-ctl start rabbitmq returned 1
    
    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/rabbitmq.rb
    
    105:   execute "#{opc_ctl} start rabbitmq" do
    106:     environment rabbitmq_env
    107:     retries 20
    108:   end
    109: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/rabbitmq.rb:105:in `from_file'
    
    execute("/opt/opscode/bin/private-chef-ctl start rabbitmq") do
      action [:run]
      retries 20
      retry_delay 2
      default_guard_interpreter :execute
      command "/opt/opscode/bin/private-chef-ctl start rabbitmq"
      backup 5
      environment {"HOSTNAME"=>"chefserver.cn.ibm.com", "TERM"=>"xterm", "LS_COLORS"=>"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:", "PATH"=>"/opt/opscode/bin:/opt/opscode/embedded/bin:/usr/bin:/bin", "PWD"=>"/root", "SVWAIT"=>"30", "HOME"=>"/root", "SHLVL"=>"2", "_"=>"/opt/opscode/embedded/service/omnibus-ctl/chef-server-ctl"}
      returns 0
      declared_type :execute
      cookbook_name "private-chef"
      recipe_name "rabbitmq"
    end
    
  * execute[restart_rabbitmq_log_service] action run
    
    ================================================================================
    Error executing action `run` on resource 'execute[restart_rabbitmq_log_service]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/rabbitmq/log ----
    STDOUT: warning: /opt/opscode/sv/rabbitmq/log: unable to open supervise/ok: file does not exist
    STDERR: 
    ---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/rabbitmq/log ----
    Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/rabbitmq/log returned 1
    
    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/enterprise/definitions/component_runit_service.rb
    
     19:   execute "restart_#{component}_log_service" do
     20:     command "#{node['runit']['sv_bin']} restart #{node['runit']['sv_dir']}/#{component}/log"
     21:     action :nothing
     22:   end
     23: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/enterprise/definitions/component_runit_service.rb:19:in `block in from_file'
    
    execute("restart_rabbitmq_log_service") do
      params {:package=>"private_chef", :log_directory=>nil, :svlogd_size=>nil, :svlogd_num=>nil, :ha=>nil, :control=>nil, :runit_attributes=>{}, :action=>:enable, :name=>"rabbitmq"}
      action [:nothing]
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "/opt/opscode/embedded/bin/sv restart /opt/opscode/sv/rabbitmq/log"
      backup 5
      returns 0
      declared_type :execute
      cookbook_name "private-chef"
      recipe_name "rabbitmq"
    end
    

Running handlers:
[2017-04-27T05:25:48+00:00] ERROR: Running exception handlers
Running handlers complete

**Comment by patrickcat** [comment]
Will use Ansible instead of this one, thanks!
