### ISSUE TITLE
superclass mismatch for class RunitService

### ISSUE THREAD

**Issue by coltrey** [chef-cookbooks/runit#227]
Is this somehow my fault?  I tried to build a branch that has not had changes since its last successful build (12 days ago) and it failed with the error below.

### Cookbook version
4.0.1
### Chef-client version
12.21.2

### Platform Details
platform=centos
platform_version=5.11
AWS/Amazon Linux

### Scenario:
Trying to run unit tests (chef exec rspec) on a wrapper cookbook around the community jenkins cookbook, which depends on runit.

### Steps to Reproduce:
executing chef exec rspec in our CI environment

### Expected Result:
Tests should compile/pass

### Actual Result:

```
================================================================================
Recipe Compile Error in /tmp/d20171129-57-ijge3h/cookbooks/runit/libraries/resource_runit_service.rb
================================================================================

TypeError
---------
superclass mismatch for class RunitService

Cookbook Trace:
---------------
  /tmp/d20171129-57-ijge3h/cookbooks/runit/libraries/resource_runit_service.rb:27:in `<class:Resource>'
  /tmp/d20171129-57-ijge3h/cookbooks/runit/libraries/resource_runit_service.rb:25:in `<class:Chef>'
  /tmp/d20171129-57-ijge3h/cookbooks/runit/libraries/resource_runit_service.rb:24:in `<top (required)>'

Relevant File Content:
----------------------
/tmp/d20171129-57-ijge3h/cookbooks/runit/libraries/resource_runit_service.rb:

 20:  
 21:  require 'chef/resource'
 22:  require 'chef/resource/service'
 23:  
 24:  class Chef
 25:    class Resource
 26:      # Missing top-level class documentation comment
 27>>     class RunitService < Chef::Resource::Service
 28:        def initialize(name, run_context = nil)
 29:          super
 30:          runit_node = runit_attributes_from_node(run_context)
 31:          @resource_name = :runit_service
 32:          @provider = Chef::Provider::RunitService
 33:          @supports = { restart: true, reload: true, status: true }
 34:          @action = :enable
 35:          @allowed_actions = [:nothing, :start, :stop, :enable, :disable, :restart, :reload, :status, :once, :hup, :cont, :term, :kill, :up, :down, :usr1, :usr2, :create]
 36:  

System Info:
------------
chef_version=12.21.2
platform=centos
platform_version=5.11
ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
program_name=/opt/chefdk/embedded/bin/rspec
executable=/opt/chefdk/embedded/bin/rspec
```

**Comment by coderanger** [comment]
Is there anything in your wrapper (under `libraries/`) which is modifying the class?

**Comment by tas50** [comment]
@coltrey What version of the jenkins cookbook are you on?

**Comment by coltrey** [comment]
@coderanger I do not have a libraries/ directory in my cookbook.
@tas50 cookbook 'jenkins', '~> 5.0.2'

**Comment by tas50** [comment]
Pretty positive I found the root cause here. Some code slipped into a commit. I'll have 4.0.3 out in a few minutes for you.

**Comment by tas50** [comment]
This wasn't noticed since we run the tests against chef 13 and this only occurs in the old 12 code

**Comment by coltrey** [comment]
Thank you.

**Comment by coltrey** [comment]
I've confirmed this is not an issue in 4.0.3
